+define+LITLE_ENDIAN 
+define+UART_ABV_ON 
+define+UVM_RGM_NO_BACKDOOR_DPI
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/apb/sv
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/uart/sv
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/sequence_lib
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/tb/sv
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/tb/tests
+incdir+$UVM_HOME/src
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl 
$UVM_HOME/src/uvm_pkg.sv
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_defines.v 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/uart_ctrl_defines.svh
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/apb/sv/apb_pkg.sv
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/uart/sv/uart_pkg.sv
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/uart_ctrl_pkg.sv
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_top.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_wb.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_transmitter.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_receiver.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_tfifo.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_rfifo.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_regs.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_debug_if.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/raminfr.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_sync_flops.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_defines.v
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/tb/sv/uart_ctrl_top.sv


