+define+LITLE_ENDIAN 
+define+UART_ABV_ON
+define+UVM_RGM_NO_BACKDOOR_DPI
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/ahb/sv
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/apb/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/uart/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/spi/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/gpio/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/sequence_lib 
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/sequence_lib
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/tb/sv/
+incdir+$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/tb/tests
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ahb2apb/rtl 
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl 
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl 
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/spi/rtl 
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl 
+incdir+$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/gpio/rtl 
+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_defines.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/spi/rtl/spi_defines.v 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/uart_ctrl_defines.svh 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/gpio_defines.svh 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/spi_defines.svh 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/apb_subsys_intf_includes.svh
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/ahb/sv/ahb_pkg.sv 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/apb/sv/apb_pkg.sv
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/uart/sv/uart_pkg.sv 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/uart_ctrl/sv/uart_ctrl_pkg.sv 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/gpio/sv/gpio_pkg.sv
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/interface_uvc_lib/spi/sv/spi_pkg.sv
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/apb_subsystem_defines.svh 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/sv/apb_subsystem_pkg.sv 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/spi/rtl/spi_clgen.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/spi/rtl/spi_shift.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/spi/rtl/spi_top.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/apb_subsystem_0.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/apb_subsystem_1.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/alut_veneer.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/gpio_veneer.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/ttc_veneer.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/smc_veneer.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/apb_subsystem/rtl/power_ctrl_veneer.v
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ahb2apb/rtl/ahb2apb.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl/alut_reg_bank.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl/alut_addr_checker.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl/alut_mem.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl/alut_age_checker.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/alut/rtl/alut.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_top.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_wb.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_transmitter.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_receiver.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_tfifo.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_rfifo.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_regs.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_debug_if.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/raminfr.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/opencores/uart16550/rtl/uart_sync_flops.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/gpio/rtl/gpio_lite_subunit.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/gpio/rtl/gpio_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_counter_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_interface_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_interrupt_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_count_rst_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_timer_counter_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/ttc/rtl/ttc_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_addr_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_cfreg_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_apb_lite_if.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_ahb_lite_if.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_counter_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_mac_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_state_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_strobe_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_wr_enable_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/smc/rtl/smc_lite.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/power_ctrl/rtl/power_ctrl_sm.v 
$UVM_REF_HOME/designs/socv/rtl/rtl_lpw/power_ctrl/rtl/power_ctrl.v 
$UVM_REF_HOME/soc_verification_lib/sv_cb_ex_lib/apb_subsystem/tb/sv/apb_subsystem_top.sv 
